export const ActionType = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    LOAD_PERFORMERS: 'LOAD_PERFORMERS',
    LOAD_PERFORMER_PROFILE: 'LOAD_PERFORMER_PROFILE',
    LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',

    LOAD_POSTS: 'LOAD_POSTS',
    ADD_POST: 'ADD_POST',
    DELETE_POST: 'DELETE_POST',
    UPDATE_POST: 'UPDATE_POST',
    LIKE_POST: 'LIKE_POST',
    COMMENT_POST: 'COMMENT_POST',

    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT'
}